# Generated by Django 4.2.5 on 2023-09-10 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_file", models.FileField(upload_to="raw_uploads/")),
                ("last_check", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "waiting"),
                            ("success", "success"),
                            ("in queue", "in queue"),
                            ("fail", "fail"),
                        ],
                        default="waiting",
                        max_length=32,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=256)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LintFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linter_output",
                    models.FileField(blank=True, default=None, null=True, upload_to="linter_output/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "waiting"),
                            ("success", "success"),
                            ("in queue", "in queue"),
                            ("fail", "fail"),
                        ],
                        default="waiting",
                        max_length=32,
                    ),
                ),
                (
                    "linter",
                    models.CharField(
                        choices=[
                            ("flake8", "flake8"),
                            ("ruff", "ruff"),
                            ("mypy", "mypy"),
                        ],
                        default="flake8",
                        max_length=32,
                    ),
                ),
                ("mail_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "raw_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="checker.file",
                    ),
                ),
            ],
        ),
    ]
